Name: Chinmay Ghule
MIS: 112415054
Assignment 2

## Q1

In [ ]:
import numpy as np

def binarize_by_row_mean(arr):
    """Return a binary matrix: 1 where an element exceeds its own row mean, else 0."""
    row_means = arr.mean(axis=1, keepdims=True)
    return (arr > row_means).astype(int)

binary = binarize_by_row_mean(A)

counts = binary.sum(axis=1)
best = np.flatnonzero(counts == counts.max())

print("Binary matrix:\n", binary)
print("\nCount above row mean:", counts)
print("Row with the most elements above their mean:", best)

Binary matrix:
 [[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]

Count above row mean: [2 2 2 2]
Row with the most elements above their mean: [0 1 2 3]


## Q2

In [9]:
X = np.array([[10,100,5],[12,110,6],[11,105,7],[13,500,6],[14,108,8],[15,115,9]])
print(X.shape)

mu  = X.mean(axis=0)
sd  = X.std(axis=0)
med = np.median(X, axis=0)
print(mu, mu.shape)

mask = np.abs(X - mu) > 2 * sd
print(mask)

X_clean = np.where(mask, med, X)

print(X_clean)
print(X)

(6, 3)
[ 12.5        173.           6.83333333] (3,)
[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False False]]
[[ 10. 100.   5.]
 [ 12. 110.   6.]
 [ 11. 105.   7.]
 [ 13. 109.   6.]
 [ 14. 108.   8.]
 [ 15. 115.   9.]]
[[ 10 100   5]
 [ 12 110   6]
 [ 11 105   7]
 [ 13 500   6]
 [ 14 108   8]
 [ 15 115   9]]


## Q3

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A','B','C','D','E','F','G','H'],
    'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],
    'Gender': ['F','M','F','M','M','F','F','M'],
    'Marks': [85,72,91,65,78,88,95,70],
    'Attendance': [92,81,96,72,85,90,98,75]})

print(df)

  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
1       B        CSE      M     72          81
2       C        ECE      F     91          96
3       D        ECE      M     65          72
4       E        CSE      M     78          85
5       F        ECE      F     88          90
6       G        CSE      F     95          98
7       H        ECE      M     70          75


In [11]:
# Part 1:
dept_avg_marks = df.groupby('Department')['Marks'].mean()
print("1. Average marks by department:\n", dept_avg_marks, "\n")

# Part 2:
dept_gender_avg = df.groupby(['Department', 'Gender'])['Marks'].mean()
print("2. Average marks by department and gender:\n", dept_gender_avg, "\n")

# Part 3:
toppers = df.loc[df.groupby('Department')['Marks'].idxmax()]
print("3. Highest scorer per department:\n", toppers, "\n")

# Part 4:
dept_mean_per_row = df.groupby('Department')['Marks'].transform('mean')
above_avg = df[df['Marks'] > dept_mean_per_row]
print("4. Students above their department average:\n", above_avg, "\n")

# Part 5:
dept_attendance = df.groupby('Department')['Attendance'].mean()
print("5. Average attendance:\n", dept_attendance)
print("   Highest:", dept_attendance.idxmax())

1. Average marks by department:
 Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64 

2. Average marks by department and gender:
 Department  Gender
CSE         F         90.0
            M         75.0
ECE         F         89.5
            M         67.5
Name: Marks, dtype: float64 

3. Highest scorer per department:
   Student Department Gender  Marks  Attendance
6       G        CSE      F     95          98
2       C        ECE      F     91          96 

4. Students above their department average:
   Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
2       C        ECE      F     91          96
5       F        ECE      F     88          90
6       G        CSE      F     95          98 

5. Average attendance:
 Department
CSE    89.00
ECE    83.25
Name: Attendance, dtype: float64
   Highest: CSE


## Q4

In [12]:
df = pd.DataFrame({
    'ID':    [101,102,103,101,104,102,105],
    'Name':  ['A','B','C','A','D','B','E'],
    'Age':   [20,21,22,20,23,21,24],
    'Score': [80,75,90,85,88,75,92]})
print(df)



    ID Name  Age  Score
0  101    A   20     80
1  102    B   21     75
2  103    C   22     90
3  101    A   20     85
4  104    D   23     88
5  102    B   21     75
6  105    E   24     92


In [13]:
# Part 1:
print("Later copies only:\n", df[df.duplicated('ID')], "\n")
print("All rows in a duplicate group:\n", df[df.duplicated('ID', keep=False)], "\n")
print("Duplicated IDs:", df.loc[df.duplicated('ID'), 'ID'].unique(), "\n")

# Part 2:
print("Distinct values per column, per ID:\n", df.groupby('ID').nunique(), "\n")

# Part 3 & 4:
clean = (df.sort_values('Score', ascending=False)
           .drop_duplicates('ID', keep='first')
           .sort_values('ID')
           .reset_index(drop=True))
print("Clean DataFrame:\n", clean, "\n")

# Part 5:
print("Records removed:", len(df) - len(clean))

Later copies only:
     ID Name  Age  Score
3  101    A   20     85
5  102    B   21     75 

All rows in a duplicate group:
     ID Name  Age  Score
0  101    A   20     80
1  102    B   21     75
3  101    A   20     85
5  102    B   21     75 

Duplicated IDs: [101 102] 

Distinct values per column, per ID:
      Name  Age  Score
ID                   
101     1    1      2
102     1    1      1
103     1    1      1
104     1    1      1
105     1    1      1 

Clean DataFrame:
     ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92 

Records removed: 2


## Q5

In [14]:
df = pd.DataFrame({
    'Date': ['2026-01-01','2026-01-02','2026-01-04',
             '2026-01-05','2026-01-08','2026-01-09'],
    'Sales': [100,120,150,130,180,200]})

In [15]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

full_range = pd.date_range(df.index.min(), df.index.max(), freq='D')
missing = full_range.difference(df.index)
print("Missing dates:", missing)

df = df.reindex(full_range)
print(df)

df['roll_default'] = df['Sales'].rolling(3).mean()
print(df)

Missing dates: DatetimeIndex(['2026-01-03', '2026-01-06', '2026-01-07'], dtype='datetime64[ns]', freq=None)
            Sales
2026-01-01  100.0
2026-01-02  120.0
2026-01-03    NaN
2026-01-04  150.0
2026-01-05  130.0
2026-01-06    NaN
2026-01-07    NaN
2026-01-08  180.0
2026-01-09  200.0
            Sales  roll_default
2026-01-01  100.0           NaN
2026-01-02  120.0           NaN
2026-01-03    NaN           NaN
2026-01-04  150.0           NaN
2026-01-05  130.0           NaN
2026-01-06    NaN           NaN
2026-01-07    NaN           NaN
2026-01-08  180.0           NaN
2026-01-09  200.0           NaN


In [16]:
df['roll_mp1'] = df['Sales'].rolling(3, min_periods=1).mean()
df['roll_3D']  = df['Sales'].rolling('3D', min_periods=1).mean()
print(df)

peak_date = df['roll_mp1'].idxmax()
print("Peak rolling average on", peak_date.date(), "at", df['roll_mp1'].max())

            Sales  roll_default  roll_mp1  roll_3D
2026-01-01  100.0           NaN     100.0    100.0
2026-01-02  120.0           NaN     110.0    110.0
2026-01-03    NaN           NaN     110.0    110.0
2026-01-04  150.0           NaN     135.0    135.0
2026-01-05  130.0           NaN     140.0    140.0
2026-01-06    NaN           NaN     140.0    140.0
2026-01-07    NaN           NaN     130.0    130.0
2026-01-08  180.0           NaN     180.0    180.0
2026-01-09  200.0           NaN     190.0    190.0
Peak rolling average on 2026-01-09 at 190.0


## Q6

In [7]:
P = np.array([[1,2],[4,6],[7,3],[2,8],[9,5]])
print(P.shape)

print(P[:, None, :].shape)
print(P[None, :, :].shape)

diff = P[:, None, :] - P[None, :, :]
print(diff.shape)

D = np.sqrt((diff ** 2).sum(axis=-1))
print(D.shape)
print(D)

print(np.allclose(np.diag(D), 0))
print(np.allclose(D, D.T))

i, j = np.unravel_index(D.argmax(), D.shape)
print("Farthest pair: points", i, "and", j)
print("Distance:", D[i, j])

(5, 2)
(5, 1, 2)
(1, 5, 2)
(5, 5, 2)
(5, 5)
[[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]
True
True
Farthest pair: points 0 and 4
Distance: 8.54400374531753


## Q7